name: og_messenger
description: OG Messenger - A serverless LAN messenger for private networks
publish_to: none
version: 1.0.0
environment:
  sdk: ^3.11.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.2.1
  sqflite: ^2.4.1
  path: ^1.9.0
  path_provider: ^2.1.5
  uuid: ^4.5.3
  shared_preferences: ^2.3.4
  flutter_local_notifications: ^20.1.0
  json_annotation: ^4.11.0
  package_info_plus: ^9.0.0
  device_info_plus: ^12.3.0
  network_info_plus: ^6.0.2
  permission_handler: ^11.3.1
  crypto: ^3.0.5
  pointycastle: ^4.0.0
  asn1lib: ^1.5.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.14.2
flutter:
  uses-material-design: true
  assets:
    - images/og_messenger.png
    - images/og_messenger.dark.png
flutter_launcher_icons:
  android: true
  ios: true
  macos:
    generate: true
    image_path: images/og_messenger_icon.dark.png
  windows:
    generate: true
    image_path: images/og_messenger_icon.dark.png
  linux: true
  image_path: images/og_messenger_icon.dark.png
  image_path_android: images/og_messenger_icon.png
  image_path_ios: images/og_messenger_icon.dark.png
  adaptive_icon_background: '#FFFFFF'
  adaptive_icon_foreground: images/og_messenger_icon.png
  adaptive_icon_foreground_light: images/og_messenger_icon.png
  adaptive_icon_foreground_dark: images/og_messenger_icon.dark.png
