name: og_messenger
description: OG Messenger - A serverless LAN messenger for private networks
publish_to: none
version: 1.2.0
environment:
  sdk: ^3.11.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  sqflite: ^2.4.1
  path: ^1.9.0
  path_provider: ^2.1.5
  uuid: ^4.5.1
  shared_preferences: ^2.3.4
  flutter_local_notifications: ^18.0.1
  json_annotation: ^4.9.0
  package_info_plus: ^8.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
flutter:
  uses-material-design: true
