name: Build

on:
  workflow_call:
    inputs:
      version:
        description: A build version to add to the name
        required: true
        type: string

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      BUILD_NAME: OG-Messenger-Android-${{ inputs.version }}.apk
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - run: flutter pub get
      - run: flutter build apk --release
      - run: mv build/app/outputs/flutter-apk/app-release.apk "$BUILD_NAME"
      - uses: actions/upload-artifact@v6
        with:
          name: build-android
          path: ${{ env.BUILD_NAME }}
          retention-days: 7

  build-ios:
    runs-on: macos-latest
    env:
      BUILD_NAME: OG-Messenger-iOS-${{ inputs.version }}.ipa
    steps:
      - uses: actions/checkout@v6
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - run: flutter pub get
      - run: flutter build ipa --release --no-codesign
      - run: mv build/ios/ipa/*.ipa "$BUILD_NAME"
      - uses: actions/upload-artifact@v6
        with:
          name: build-ios
          path: ${{ env.BUILD_NAME }}
          retention-days: 7

  build-linux:
    runs-on: ubuntu-latest
    env:
      BUILD_NAME: OG-Messenger-Linux-${{ inputs.version }}.tar.gz
    steps:
      - uses: actions/checkout@v6
      - run: | # shell
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - run: flutter pub get
      - run: flutter build linux --release
      - run: | # shell
          cd build/linux/x64/release/bundle
          tar -czf "../../../../../$BUILD_NAME" *
      - uses: actions/upload-artifact@v5
        with:
          name: build-linux
          path: ${{ env.BUILD_NAME }}
          retention-days: 7

  build-macos:
    runs-on: macos-latest
    env:
      BUILD_NAME: OG-Messenger-macOS-${{ inputs.version }}.app
    steps:
      - uses: actions/checkout@v6
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - run: flutter pub get
      - run: flutter build macos --release
      - run: | # shell
          cd build/macos/Build/Products/Release
          mv "../../../../../$BUILD_NAME" og_messenger.app
      - uses: actions/upload-artifact@v6
        with:
          name: build-macos
          path: ${{ env.BUILD_NAME }}
          retention-days: 7

  build-windows:
    runs-on: windows-latest
    env:
      BUILD_NAME: OG-Messenger-Windows-${{ inputs.version }}.zip
    steps:
      - uses: actions/checkout@v6
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - run: flutter pub get
      - run: flutter build windows --release
      - run: Compress-Archive -Path build/windows/x64/runner/Release/* -DestinationPath ${{ env.BUILD_NAME }}
      - uses: actions/upload-artifact@v5
        with:
          name: build-windows
          path: ${{ env.BUILD_NAME }}
          retention-days: 7
