name: release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release-test:
    concurrency:
      cancel-in-progress: true
      group: release-test
    uses: ./.github/workflows/test.yml

  release-github:
    needs: release-test
    runs-on: ubuntu-latest
    concurrency:
      group: release-github
    permissions:
      contents: write
      issues: write
      pull-requests: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      version: ${{ steps.release.outputs.version }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  release-build:
    needs: release-github
    if: ${{ needs.release-github.outputs.release_created }}
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ needs.release-github.outputs.version }}

  release-assets:
    needs: [release-github, release-build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: release-assets-${{ needs.release-github.outputs.version }}
    steps:
      - uses: actions/download-artifact@v7
        with:
          path: .
          merge-multiple: true
      - uses: softprops/action-gh-release@v2
        with:
          draft: false
          tag_name: ${{ needs.release-github.outputs.tag_name }}
          files: ./*
